apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vind.fullname" . }}-config
data:
  DB_HOST: "{{ .Release.Name }}-mysql"
  DB_PORT: "{{ .Values.database.port }}"
  DB_NAME: "{{ .Values.database.name }}"